### ISSUE TITLE
Single Color Scheme

### ISSUE THREAD

**Issue by gonsie** [InspectorMustache/base16-builder-python#1]
Is there a way to specify a single color scheme to clone and/or build? As a way to do color scheme development.

BTW, thank for the easy-to-use tool!

**Comment by InspectorMustache** [comment]
Well, there is now. ;) For cloning you can edit ./sources/schemes/list.yaml and add/remove repositories as you wish. Then, to prevent that file from being overwritten when updating, use `update -c`.
For building, you can use the -s flag to specify a scheme file name.
