### ISSUE TITLE
Correct Readme

### ISSUE THREAD

**Issue by AXGKl** [InspectorMustache/base16-builder-python#14]
Thanks for the tool. 

This one does not work for me:
```
pybase16 inject -s schemes/default/ocean.yaml -f ~/.gtkrc-2.0.mine -f ~/.config/dunst/dunstrc -f ~/.config/i3/config -f ~/.config/termite/config -f ~/.config/zathura/zathurarc
```
scheme file not found like that.

Should be like in your travis test:

```
cd <your_base_dir>
pybase16 inject -s ocean -f ~/.gtkrc-2.0.mine -f ~/.config/dunst/dunstrc -f ~/.config/i3/config -f ~/.config/termite/config -f ~/.config/zathura/zathurarc

``` 
and to really make it clear maybe a non default one:

    pybase16 inject -s black-metal-burzum -f /home/gk/.Xresources

----

apropos .Xresources - too minor for an issue imho, just a big ugly:
The tool swallows the last newline, at least in .Xresources type of target file, resulting in:

    /home/gk/.Xresources:59: warning: End of input with no newline, supplemented newline

when `xrdb ~./Xresources` is run after injection. Not a big deal here but I think it should be corrected. Thanks again.

**Comment by InspectorMustache** [comment]
I fixed the readme, sorry for the delay. I don't think I understand what the advantage of your non-default exampe is and what exactly makes it "non-default" but as a general rule in life, I try to keep Burzum out of things.

I myself now just use shell scripts to inject schemes into config files. Still, I'll fix that newline issue eventually.

**Comment by InspectorMustache** [comment]
Fixed the issue with trailing newlines.  This was a very easy fix, sorry for my laziness.  This is not pushed to PyPI yet, but you can try it from the git repo.

**Comment by InspectorMustache** [comment]
Fix pushed to PyPI, let me know if you're still having issues.
