### ISSUE TITLE
Update to base16 0.9.1

### ISSUE THREAD

**Issue by gma** [InspectorMustache/base16-builder-python#15]
I've just cloned `master` in order to give this base16-builder business a try (it looks great) and seem to have run into a bug.

I ran these commands successfully:

    $ python3 -mvenv .
    $ . ./bin/activate
    $ pip install
    $ pybase16 update

Then I did the build, which mostly worked. It printed this part-way through its output, before hanging:

```
$ pybase16 build
Building colorschemes for scheme "Material Vivid"…
Building colorschemes for scheme "Tomorrow"…
Building colorschemes for scheme "Tomorrow Night"…
Building colorschemes for scheme "Mocha"…
Building colorschemes for scheme "Ocean"…
Building colorschemes for scheme "Rebecca"…
Exception in thread Thread-38:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/graham/tmp/base16/base16-builder-python/lib/python3.7/site-packages/pybase16_builder/builder.py", line 161, in build_single_worker
    build_single(scheme_file, templates, base_output_dir)
  File "/home/graham/tmp/base16/base16-builder-python/lib/python3.7/site-packages/pybase16_builder/builder.py", line 126, in build_single
    format_scheme(scheme, scheme_slug)
  File "/home/graham/tmp/base16/base16-builder-python/lib/python3.7/site-packages/pybase16_builder/builder.py", line 99, in format_scheme
    int(scheme['{}-hex-r'.format(base)], 16))
ValueError: invalid literal for int() with base 16: '#2'

Built colorschemes for scheme "Summerfruit Light".
Built colorschemes for scheme "Heetch Light".
Built colorschemes for scheme "Mexico Light".
Built colorschemes for scheme "Synth Midnight Dark".
Built colorschemes for scheme "One Light".
```

There's one process and 39 threads, and I suspect they're all blocked because the main thread is waiting for that thread that couldn't parse its input?

Let me know if you need any more info. It doesn't look like it matters, but this is with Python 3.7.3 on Pop!_OS 19.04.

Cheers!

**Comment by reneatzi** [comment]
Same error here on arch with Python 3.7.4.

I get the error on a different colorscheme. I tried to remove the faulty one and build it again, but still got the same error. Just on a different colorscheme.

**Comment by gma** [comment]
@reneatzi I suspect that the thread that's throwing the error isn't processing the one whose name was printed on the previous line; there could well be quite a few threads running at once, and that error could have come from any of them. I've not checked the code though - this is just how I imagine it's working. Perhaps we should grep for `#2` to narrow down the potential culprits (I'm not on the right computer right now to try it).

**Comment by InspectorMustache** [comment]
First of all, thanks for reporting!
There's two things here that need to be considered.  First, why does building fail for some schemes and then, why does a build error cause the script to hang.

So for the first part, my initial guess would be that these are schemes that adhere to the new base16 standard (0.9.1) which the builder doesn't support yet.  Regarding the hanging issue, I had a quick look at the code and I am pretty sure, the program blocks because the thread doesn't signal task_done() to the queue when it encounters an exception.  That should be easy to fix.  Updating the builder to 0.9.1 actually shouldn't be that difficult either, but might take a little time.  I'll try to fix that in the coming week or so.

**Comment by InspectorMustache** [comment]
Okay, so the builder shouldn't hang anymore when there's an issue with a single thread

**Comment by gma** [comment]
Nicely, thanks @InspectorMustache. I just updated, ran it again, and got your nice helpful error message instead...

```
Error building /home/graham/tmp/base16/base16-builder-python/schemes/gigavolt/gigavolt.yaml:
	invalid literal for int() with base 16: '#2'Building colorschemes for scheme "Brogrammer"…
```

I think can do without the Brogrammer... ;-)

**Comment by reneatzi** [comment]
> Okay, so the builder shouldn't hang anymore when there's an issue with a single thread ([96383d0](https://github.com/InspectorMustache/base16-builder-python/commit/96383d01f510d734b85dcf29175af09815af8a5b)).

Thank you, can confirm that it is working now.

**Comment by InspectorMustache** [comment]
Good to hear, I changed the title of the issue to better reflect what's still left to do.

**Comment by InspectorMustache** [comment]
Actually this had nothing to do with the update to the base16 specification, that scheme is just badly formatted. Aaaaanyway....
